<?php
/**
 * CampaignResponseModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\retailmedia\experimental\Model;

use \ArrayAccess;
use \criteo\api\retailmedia\experimental\ObjectSerializer;

/**
 * CampaignResponseModel Class Doc Comment
 *
 * @category Class
 * @description A Retail Media Campaign used to represent an advertiser&#39;s marketing objective
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CampaignResponseModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CampaignResponseModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'string',
        'attribution_settings' => '\criteo\api\retailmedia\experimental\Model\AttributionSettingsModel',
        'bill_by_retailer_id' => 'string',
        'buy_type' => 'string',
        'campaign_type' => 'string',
        'company_name' => 'string',
        'created_at' => '\DateTime',
        'drawable_balance_ids' => 'string[]',
        'id' => 'string',
        'name' => 'string',
        'on_behalf_company_name' => 'string',
        'onsite_display_details' => '\criteo\api\retailmedia\experimental\Model\OnsiteDisplayDetailsModel',
        'regulated_category' => 'string',
        'schedule_details' => '\criteo\api\retailmedia\experimental\Model\ScheduleDetailsModel',
        'sponsored_products_details' => '\criteo\api\retailmedia\experimental\Model\SponsoredProductsDetailsModel',
        'status' => 'string',
        'updated_at' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => null,
        'attribution_settings' => null,
        'bill_by_retailer_id' => null,
        'buy_type' => null,
        'campaign_type' => null,
        'company_name' => null,
        'created_at' => 'date-time',
        'drawable_balance_ids' => null,
        'id' => null,
        'name' => null,
        'on_behalf_company_name' => null,
        'onsite_display_details' => null,
        'regulated_category' => null,
        'schedule_details' => null,
        'sponsored_products_details' => null,
        'status' => null,
        'updated_at' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => false,
		'attribution_settings' => false,
		'bill_by_retailer_id' => true,
		'buy_type' => false,
		'campaign_type' => false,
		'company_name' => true,
		'created_at' => false,
		'drawable_balance_ids' => false,
		'id' => true,
		'name' => false,
		'on_behalf_company_name' => true,
		'onsite_display_details' => true,
		'regulated_category' => false,
		'schedule_details' => true,
		'sponsored_products_details' => true,
		'status' => false,
		'updated_at' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'attribution_settings' => 'attributionSettings',
        'bill_by_retailer_id' => 'billByRetailerId',
        'buy_type' => 'buyType',
        'campaign_type' => 'campaignType',
        'company_name' => 'companyName',
        'created_at' => 'createdAt',
        'drawable_balance_ids' => 'drawableBalanceIds',
        'id' => 'id',
        'name' => 'name',
        'on_behalf_company_name' => 'onBehalfCompanyName',
        'onsite_display_details' => 'onsiteDisplayDetails',
        'regulated_category' => 'regulatedCategory',
        'schedule_details' => 'scheduleDetails',
        'sponsored_products_details' => 'sponsoredProductsDetails',
        'status' => 'status',
        'updated_at' => 'updatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'attribution_settings' => 'setAttributionSettings',
        'bill_by_retailer_id' => 'setBillByRetailerId',
        'buy_type' => 'setBuyType',
        'campaign_type' => 'setCampaignType',
        'company_name' => 'setCompanyName',
        'created_at' => 'setCreatedAt',
        'drawable_balance_ids' => 'setDrawableBalanceIds',
        'id' => 'setId',
        'name' => 'setName',
        'on_behalf_company_name' => 'setOnBehalfCompanyName',
        'onsite_display_details' => 'setOnsiteDisplayDetails',
        'regulated_category' => 'setRegulatedCategory',
        'schedule_details' => 'setScheduleDetails',
        'sponsored_products_details' => 'setSponsoredProductsDetails',
        'status' => 'setStatus',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'attribution_settings' => 'getAttributionSettings',
        'bill_by_retailer_id' => 'getBillByRetailerId',
        'buy_type' => 'getBuyType',
        'campaign_type' => 'getCampaignType',
        'company_name' => 'getCompanyName',
        'created_at' => 'getCreatedAt',
        'drawable_balance_ids' => 'getDrawableBalanceIds',
        'id' => 'getId',
        'name' => 'getName',
        'on_behalf_company_name' => 'getOnBehalfCompanyName',
        'onsite_display_details' => 'getOnsiteDisplayDetails',
        'regulated_category' => 'getRegulatedCategory',
        'schedule_details' => 'getScheduleDetails',
        'sponsored_products_details' => 'getSponsoredProductsDetails',
        'status' => 'getStatus',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BUY_TYPE_UNKNOWN = 'Unknown';
    public const BUY_TYPE_AUCTION = 'Auction';
    public const BUY_TYPE_PREFERRED_DEALS = 'PreferredDeals';
    public const BUY_TYPE_SPONSORSHIP = 'Sponsorship';
    public const CAMPAIGN_TYPE_UNKNOWN = 'Unknown';
    public const CAMPAIGN_TYPE_SPONSORED_PRODUCTS = 'SponsoredProducts';
    public const CAMPAIGN_TYPE_ONSITE_DISPLAY = 'OnsiteDisplay';
    public const REGULATED_CATEGORY_UNKNOWN = 'Unknown';
    public const REGULATED_CATEGORY_NONE = 'None';
    public const REGULATED_CATEGORY_ALCOHOL = 'Alcohol';
    public const STATUS_UNKNOWN = 'Unknown';
    public const STATUS_ACTIVE = 'Active';
    public const STATUS_INACTIVE = 'Inactive';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBuyTypeAllowableValues()
    {
        return [
            self::BUY_TYPE_UNKNOWN,
            self::BUY_TYPE_AUCTION,
            self::BUY_TYPE_PREFERRED_DEALS,
            self::BUY_TYPE_SPONSORSHIP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCampaignTypeAllowableValues()
    {
        return [
            self::CAMPAIGN_TYPE_UNKNOWN,
            self::CAMPAIGN_TYPE_SPONSORED_PRODUCTS,
            self::CAMPAIGN_TYPE_ONSITE_DISPLAY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRegulatedCategoryAllowableValues()
    {
        return [
            self::REGULATED_CATEGORY_UNKNOWN,
            self::REGULATED_CATEGORY_NONE,
            self::REGULATED_CATEGORY_ALCOHOL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_UNKNOWN,
            self::STATUS_ACTIVE,
            self::STATUS_INACTIVE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('attribution_settings', $data ?? [], null);
        $this->setIfExists('bill_by_retailer_id', $data ?? [], null);
        $this->setIfExists('buy_type', $data ?? [], null);
        $this->setIfExists('campaign_type', $data ?? [], null);
        $this->setIfExists('company_name', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('drawable_balance_ids', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('on_behalf_company_name', $data ?? [], null);
        $this->setIfExists('onsite_display_details', $data ?? [], null);
        $this->setIfExists('regulated_category', $data ?? [], null);
        $this->setIfExists('schedule_details', $data ?? [], null);
        $this->setIfExists('sponsored_products_details', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['attribution_settings'] === null) {
            $invalidProperties[] = "'attribution_settings' can't be null";
        }
        if ($this->container['buy_type'] === null) {
            $invalidProperties[] = "'buy_type' can't be null";
        }
        $allowedValues = $this->getBuyTypeAllowableValues();
        if (!is_null($this->container['buy_type']) && !in_array($this->container['buy_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'buy_type', must be one of '%s'",
                $this->container['buy_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['campaign_type'] === null) {
            $invalidProperties[] = "'campaign_type' can't be null";
        }
        $allowedValues = $this->getCampaignTypeAllowableValues();
        if (!is_null($this->container['campaign_type']) && !in_array($this->container['campaign_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'campaign_type', must be one of '%s'",
                $this->container['campaign_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['drawable_balance_ids'] === null) {
            $invalidProperties[] = "'drawable_balance_ids' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['name']) < 0)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 0.";
        }

        if ($this->container['regulated_category'] === null) {
            $invalidProperties[] = "'regulated_category' can't be null";
        }
        $allowedValues = $this->getRegulatedCategoryAllowableValues();
        if (!is_null($this->container['regulated_category']) && !in_array($this->container['regulated_category'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'regulated_category', must be one of '%s'",
                $this->container['regulated_category'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets attribution_settings
     *
     * @return \criteo\api\retailmedia\experimental\Model\AttributionSettingsModel
     */
    public function getAttributionSettings()
    {
        return $this->container['attribution_settings'];
    }

    /**
     * Sets attribution_settings
     *
     * @param \criteo\api\retailmedia\experimental\Model\AttributionSettingsModel $attribution_settings attribution_settings
     *
     * @return self
     */
    public function setAttributionSettings($attribution_settings)
    {
        if (is_null($attribution_settings)) {
            throw new \InvalidArgumentException('non-nullable attribution_settings cannot be null');
        }
        $this->container['attribution_settings'] = $attribution_settings;

        return $this;
    }

    /**
     * Gets bill_by_retailer_id
     *
     * @return string|null
     */
    public function getBillByRetailerId()
    {
        return $this->container['bill_by_retailer_id'];
    }

    /**
     * Sets bill_by_retailer_id
     *
     * @param string|null $bill_by_retailer_id bill_by_retailer_id
     *
     * @return self
     */
    public function setBillByRetailerId($bill_by_retailer_id)
    {
        if (is_null($bill_by_retailer_id)) {
            array_push($this->openAPINullablesSetToNull, 'bill_by_retailer_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bill_by_retailer_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bill_by_retailer_id'] = $bill_by_retailer_id;

        return $this;
    }

    /**
     * Gets buy_type
     *
     * @return string
     */
    public function getBuyType()
    {
        return $this->container['buy_type'];
    }

    /**
     * Sets buy_type
     *
     * @param string $buy_type Buy type of campaign, set only on creation.
     *
     * @return self
     */
    public function setBuyType($buy_type)
    {
        if (is_null($buy_type)) {
            throw new \InvalidArgumentException('non-nullable buy_type cannot be null');
        }
        $allowedValues = $this->getBuyTypeAllowableValues();
        if (!in_array($buy_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'buy_type', must be one of '%s'",
                    $buy_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['buy_type'] = $buy_type;

        return $this;
    }

    /**
     * Gets campaign_type
     *
     * @return string
     */
    public function getCampaignType()
    {
        return $this->container['campaign_type'];
    }

    /**
     * Sets campaign_type
     *
     * @param string $campaign_type Type of campaign, set only on creation.
     *
     * @return self
     */
    public function setCampaignType($campaign_type)
    {
        if (is_null($campaign_type)) {
            throw new \InvalidArgumentException('non-nullable campaign_type cannot be null');
        }
        $allowedValues = $this->getCampaignTypeAllowableValues();
        if (!in_array($campaign_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'campaign_type', must be one of '%s'",
                    $campaign_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['campaign_type'] = $campaign_type;

        return $this;
    }

    /**
     * Gets company_name
     *
     * @return string|null
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     *
     * @param string|null $company_name company_name
     *
     * @return self
     */
    public function setCompanyName($company_name)
    {
        if (is_null($company_name)) {
            array_push($this->openAPINullablesSetToNull, 'company_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('company_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets drawable_balance_ids
     *
     * @return string[]
     */
    public function getDrawableBalanceIds()
    {
        return $this->container['drawable_balance_ids'];
    }

    /**
     * Sets drawable_balance_ids
     *
     * @param string[] $drawable_balance_ids drawable_balance_ids
     *
     * @return self
     */
    public function setDrawableBalanceIds($drawable_balance_ids)
    {
        if (is_null($drawable_balance_ids)) {
            throw new \InvalidArgumentException('non-nullable drawable_balance_ids cannot be null');
        }
        $this->container['drawable_balance_ids'] = $drawable_balance_ids;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CampaignResponseModel., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($name) < 0)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CampaignResponseModel., must be bigger than or equal to 0.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets on_behalf_company_name
     *
     * @return string|null
     */
    public function getOnBehalfCompanyName()
    {
        return $this->container['on_behalf_company_name'];
    }

    /**
     * Sets on_behalf_company_name
     *
     * @param string|null $on_behalf_company_name on_behalf_company_name
     *
     * @return self
     */
    public function setOnBehalfCompanyName($on_behalf_company_name)
    {
        if (is_null($on_behalf_company_name)) {
            array_push($this->openAPINullablesSetToNull, 'on_behalf_company_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('on_behalf_company_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['on_behalf_company_name'] = $on_behalf_company_name;

        return $this;
    }

    /**
     * Gets onsite_display_details
     *
     * @return \criteo\api\retailmedia\experimental\Model\OnsiteDisplayDetailsModel|null
     */
    public function getOnsiteDisplayDetails()
    {
        return $this->container['onsite_display_details'];
    }

    /**
     * Sets onsite_display_details
     *
     * @param \criteo\api\retailmedia\experimental\Model\OnsiteDisplayDetailsModel|null $onsite_display_details onsite_display_details
     *
     * @return self
     */
    public function setOnsiteDisplayDetails($onsite_display_details)
    {
        if (is_null($onsite_display_details)) {
            array_push($this->openAPINullablesSetToNull, 'onsite_display_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('onsite_display_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['onsite_display_details'] = $onsite_display_details;

        return $this;
    }

    /**
     * Gets regulated_category
     *
     * @return string
     */
    public function getRegulatedCategory()
    {
        return $this->container['regulated_category'];
    }

    /**
     * Sets regulated_category
     *
     * @param string $regulated_category Regulated category the campaign advertises in, set only on creation.
     *
     * @return self
     */
    public function setRegulatedCategory($regulated_category)
    {
        if (is_null($regulated_category)) {
            throw new \InvalidArgumentException('non-nullable regulated_category cannot be null');
        }
        $allowedValues = $this->getRegulatedCategoryAllowableValues();
        if (!in_array($regulated_category, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'regulated_category', must be one of '%s'",
                    $regulated_category,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['regulated_category'] = $regulated_category;

        return $this;
    }

    /**
     * Gets schedule_details
     *
     * @return \criteo\api\retailmedia\experimental\Model\ScheduleDetailsModel|null
     */
    public function getScheduleDetails()
    {
        return $this->container['schedule_details'];
    }

    /**
     * Sets schedule_details
     *
     * @param \criteo\api\retailmedia\experimental\Model\ScheduleDetailsModel|null $schedule_details schedule_details
     *
     * @return self
     */
    public function setScheduleDetails($schedule_details)
    {
        if (is_null($schedule_details)) {
            array_push($this->openAPINullablesSetToNull, 'schedule_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('schedule_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['schedule_details'] = $schedule_details;

        return $this;
    }

    /**
     * Gets sponsored_products_details
     *
     * @return \criteo\api\retailmedia\experimental\Model\SponsoredProductsDetailsModel|null
     */
    public function getSponsoredProductsDetails()
    {
        return $this->container['sponsored_products_details'];
    }

    /**
     * Sets sponsored_products_details
     *
     * @param \criteo\api\retailmedia\experimental\Model\SponsoredProductsDetailsModel|null $sponsored_products_details sponsored_products_details
     *
     * @return self
     */
    public function setSponsoredProductsDetails($sponsored_products_details)
    {
        if (is_null($sponsored_products_details)) {
            array_push($this->openAPINullablesSetToNull, 'sponsored_products_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sponsored_products_details', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sponsored_products_details'] = $sponsored_products_details;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Campaign status, derived from the status of Line Items it holds; active if at least  one line item is active.
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


