<?php
/**
 * CatalogIngestionSummary
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\retailmedia\experimental\Model;

use \ArrayAccess;
use \criteo\api\retailmedia\experimental\ObjectSerializer;

/**
 * CatalogIngestionSummary Class Doc Comment
 *
 * @category Class
 * @description Summary report of a catalog ingestion: identification, timing, status, volume, delta and data quality.
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CatalogIngestionSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CatalogIngestionSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'component_id' => 'string',
        'data_quality' => '\criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDataQuality',
        'delta' => '\criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDelta',
        'duration' => 'string',
        'end_time' => '\DateTime',
        'error' => '\criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingError',
        'ingestion_status' => '\criteo\api\retailmedia\experimental\Model\IngestionStatus',
        'ingestion_type' => '\criteo\api\retailmedia\experimental\Model\IngestionType',
        'merchant_id' => 'string',
        'merchant_name' => 'string',
        'multi_source' => '\criteo\api\retailmedia\experimental\Model\MultiSourceReporting',
        'multi_source_reporting_status' => '\criteo\api\retailmedia\experimental\Model\MultiSourceReportingStatus',
        'start_time' => '\DateTime',
        'trigger' => '\criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingTrigger',
        'volume' => '\criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingVolume'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'component_id' => null,
        'data_quality' => null,
        'delta' => null,
        'duration' => null,
        'end_time' => 'date-time',
        'error' => null,
        'ingestion_status' => null,
        'ingestion_type' => null,
        'merchant_id' => null,
        'merchant_name' => null,
        'multi_source' => null,
        'multi_source_reporting_status' => null,
        'start_time' => 'date-time',
        'trigger' => null,
        'volume' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'component_id' => true,
		'data_quality' => true,
		'delta' => true,
		'duration' => true,
		'end_time' => true,
		'error' => true,
		'ingestion_status' => false,
		'ingestion_type' => false,
		'merchant_id' => true,
		'merchant_name' => true,
		'multi_source' => true,
		'multi_source_reporting_status' => false,
		'start_time' => false,
		'trigger' => true,
		'volume' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'component_id' => 'componentId',
        'data_quality' => 'dataQuality',
        'delta' => 'delta',
        'duration' => 'duration',
        'end_time' => 'endTime',
        'error' => 'error',
        'ingestion_status' => 'ingestionStatus',
        'ingestion_type' => 'ingestionType',
        'merchant_id' => 'merchantId',
        'merchant_name' => 'merchantName',
        'multi_source' => 'multiSource',
        'multi_source_reporting_status' => 'multiSourceReportingStatus',
        'start_time' => 'startTime',
        'trigger' => 'trigger',
        'volume' => 'volume'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'component_id' => 'setComponentId',
        'data_quality' => 'setDataQuality',
        'delta' => 'setDelta',
        'duration' => 'setDuration',
        'end_time' => 'setEndTime',
        'error' => 'setError',
        'ingestion_status' => 'setIngestionStatus',
        'ingestion_type' => 'setIngestionType',
        'merchant_id' => 'setMerchantId',
        'merchant_name' => 'setMerchantName',
        'multi_source' => 'setMultiSource',
        'multi_source_reporting_status' => 'setMultiSourceReportingStatus',
        'start_time' => 'setStartTime',
        'trigger' => 'setTrigger',
        'volume' => 'setVolume'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'component_id' => 'getComponentId',
        'data_quality' => 'getDataQuality',
        'delta' => 'getDelta',
        'duration' => 'getDuration',
        'end_time' => 'getEndTime',
        'error' => 'getError',
        'ingestion_status' => 'getIngestionStatus',
        'ingestion_type' => 'getIngestionType',
        'merchant_id' => 'getMerchantId',
        'merchant_name' => 'getMerchantName',
        'multi_source' => 'getMultiSource',
        'multi_source_reporting_status' => 'getMultiSourceReportingStatus',
        'start_time' => 'getStartTime',
        'trigger' => 'getTrigger',
        'volume' => 'getVolume'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('component_id', $data ?? [], null);
        $this->setIfExists('data_quality', $data ?? [], null);
        $this->setIfExists('delta', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('error', $data ?? [], null);
        $this->setIfExists('ingestion_status', $data ?? [], null);
        $this->setIfExists('ingestion_type', $data ?? [], null);
        $this->setIfExists('merchant_id', $data ?? [], null);
        $this->setIfExists('merchant_name', $data ?? [], null);
        $this->setIfExists('multi_source', $data ?? [], null);
        $this->setIfExists('multi_source_reporting_status', $data ?? [], null);
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('trigger', $data ?? [], null);
        $this->setIfExists('volume', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets component_id
     *
     * @return string|null
     */
    public function getComponentId()
    {
        return $this->container['component_id'];
    }

    /**
     * Sets component_id
     *
     * @param string|null $component_id component_id
     *
     * @return self
     */
    public function setComponentId($component_id)
    {
        if (is_null($component_id)) {
            array_push($this->openAPINullablesSetToNull, 'component_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('component_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['component_id'] = $component_id;

        return $this;
    }

    /**
     * Gets data_quality
     *
     * @return \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDataQuality|null
     */
    public function getDataQuality()
    {
        return $this->container['data_quality'];
    }

    /**
     * Sets data_quality
     *
     * @param \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDataQuality|null $data_quality data_quality
     *
     * @return self
     */
    public function setDataQuality($data_quality)
    {
        if (is_null($data_quality)) {
            array_push($this->openAPINullablesSetToNull, 'data_quality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_quality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_quality'] = $data_quality;

        return $this;
    }

    /**
     * Gets delta
     *
     * @return \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDelta|null
     */
    public function getDelta()
    {
        return $this->container['delta'];
    }

    /**
     * Sets delta
     *
     * @param \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingDelta|null $delta delta
     *
     * @return self
     */
    public function setDelta($delta)
    {
        if (is_null($delta)) {
            array_push($this->openAPINullablesSetToNull, 'delta');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delta', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delta'] = $delta;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string|null $duration Total ingestion processing time as an ISO 8601 duration.
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            array_push($this->openAPINullablesSetToNull, 'duration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('duration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return \DateTime|null
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param \DateTime|null $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            array_push($this->openAPINullablesSetToNull, 'end_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets error
     *
     * @return \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingError|null
     */
    public function getError()
    {
        return $this->container['error'];
    }

    /**
     * Sets error
     *
     * @param \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingError|null $error error
     *
     * @return self
     */
    public function setError($error)
    {
        if (is_null($error)) {
            array_push($this->openAPINullablesSetToNull, 'error');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('error', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['error'] = $error;

        return $this;
    }

    /**
     * Gets ingestion_status
     *
     * @return \criteo\api\retailmedia\experimental\Model\IngestionStatus|null
     */
    public function getIngestionStatus()
    {
        return $this->container['ingestion_status'];
    }

    /**
     * Sets ingestion_status
     *
     * @param \criteo\api\retailmedia\experimental\Model\IngestionStatus|null $ingestion_status ingestion_status
     *
     * @return self
     */
    public function setIngestionStatus($ingestion_status)
    {
        if (is_null($ingestion_status)) {
            throw new \InvalidArgumentException('non-nullable ingestion_status cannot be null');
        }
        $this->container['ingestion_status'] = $ingestion_status;

        return $this;
    }

    /**
     * Gets ingestion_type
     *
     * @return \criteo\api\retailmedia\experimental\Model\IngestionType|null
     */
    public function getIngestionType()
    {
        return $this->container['ingestion_type'];
    }

    /**
     * Sets ingestion_type
     *
     * @param \criteo\api\retailmedia\experimental\Model\IngestionType|null $ingestion_type ingestion_type
     *
     * @return self
     */
    public function setIngestionType($ingestion_type)
    {
        if (is_null($ingestion_type)) {
            throw new \InvalidArgumentException('non-nullable ingestion_type cannot be null');
        }
        $this->container['ingestion_type'] = $ingestion_type;

        return $this;
    }

    /**
     * Gets merchant_id
     *
     * @return string|null
     */
    public function getMerchantId()
    {
        return $this->container['merchant_id'];
    }

    /**
     * Sets merchant_id
     *
     * @param string|null $merchant_id merchant_id
     *
     * @return self
     */
    public function setMerchantId($merchant_id)
    {
        if (is_null($merchant_id)) {
            array_push($this->openAPINullablesSetToNull, 'merchant_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('merchant_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['merchant_id'] = $merchant_id;

        return $this;
    }

    /**
     * Gets merchant_name
     *
     * @return string|null
     */
    public function getMerchantName()
    {
        return $this->container['merchant_name'];
    }

    /**
     * Sets merchant_name
     *
     * @param string|null $merchant_name merchant_name
     *
     * @return self
     */
    public function setMerchantName($merchant_name)
    {
        if (is_null($merchant_name)) {
            array_push($this->openAPINullablesSetToNull, 'merchant_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('merchant_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['merchant_name'] = $merchant_name;

        return $this;
    }

    /**
     * Gets multi_source
     *
     * @return \criteo\api\retailmedia\experimental\Model\MultiSourceReporting|null
     */
    public function getMultiSource()
    {
        return $this->container['multi_source'];
    }

    /**
     * Sets multi_source
     *
     * @param \criteo\api\retailmedia\experimental\Model\MultiSourceReporting|null $multi_source multi_source
     *
     * @return self
     */
    public function setMultiSource($multi_source)
    {
        if (is_null($multi_source)) {
            array_push($this->openAPINullablesSetToNull, 'multi_source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('multi_source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['multi_source'] = $multi_source;

        return $this;
    }

    /**
     * Gets multi_source_reporting_status
     *
     * @return \criteo\api\retailmedia\experimental\Model\MultiSourceReportingStatus|null
     */
    public function getMultiSourceReportingStatus()
    {
        return $this->container['multi_source_reporting_status'];
    }

    /**
     * Sets multi_source_reporting_status
     *
     * @param \criteo\api\retailmedia\experimental\Model\MultiSourceReportingStatus|null $multi_source_reporting_status multi_source_reporting_status
     *
     * @return self
     */
    public function setMultiSourceReportingStatus($multi_source_reporting_status)
    {
        if (is_null($multi_source_reporting_status)) {
            throw new \InvalidArgumentException('non-nullable multi_source_reporting_status cannot be null');
        }
        $this->container['multi_source_reporting_status'] = $multi_source_reporting_status;

        return $this;
    }

    /**
     * Gets start_time
     *
     * @return \DateTime|null
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param \DateTime|null $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets trigger
     *
     * @return \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingTrigger|null
     */
    public function getTrigger()
    {
        return $this->container['trigger'];
    }

    /**
     * Sets trigger
     *
     * @param \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingTrigger|null $trigger trigger
     *
     * @return self
     */
    public function setTrigger($trigger)
    {
        if (is_null($trigger)) {
            array_push($this->openAPINullablesSetToNull, 'trigger');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('trigger', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['trigger'] = $trigger;

        return $this;
    }

    /**
     * Gets volume
     *
     * @return \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingVolume|null
     */
    public function getVolume()
    {
        return $this->container['volume'];
    }

    /**
     * Sets volume
     *
     * @param \criteo\api\retailmedia\experimental\Model\CatalogIngestionReportingVolume|null $volume volume
     *
     * @return self
     */
    public function setVolume($volume)
    {
        if (is_null($volume)) {
            array_push($this->openAPINullablesSetToNull, 'volume');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('volume', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['volume'] = $volume;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


