<?php
/**
 * MultiSourceConfiguration
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Experimental
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\retailmedia\experimental\Model;

use \ArrayAccess;
use \criteo\api\retailmedia\experimental\ObjectSerializer;

/**
 * MultiSourceConfiguration Class Doc Comment
 *
 * @category Class
 * @description Multi-Source Catalog configuration applied to the ingestion: main component, number of sources, matching keys and attribute mappings.
 * @package  criteo\api\retailmedia\experimental
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MultiSourceConfiguration implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MultiSourceConfiguration';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'attribute_mappings' => '\criteo\api\retailmedia\experimental\Model\MultiSourceAttributeMapping[]',
        'enabled' => 'bool',
        'main_component_id' => 'int',
        'matching_keys' => 'string[]',
        'sources_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'attribute_mappings' => null,
        'enabled' => null,
        'main_component_id' => 'int32',
        'matching_keys' => null,
        'sources_count' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'attribute_mappings' => true,
		'enabled' => false,
		'main_component_id' => false,
		'matching_keys' => true,
		'sources_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attribute_mappings' => 'attributeMappings',
        'enabled' => 'enabled',
        'main_component_id' => 'mainComponentId',
        'matching_keys' => 'matchingKeys',
        'sources_count' => 'sourcesCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attribute_mappings' => 'setAttributeMappings',
        'enabled' => 'setEnabled',
        'main_component_id' => 'setMainComponentId',
        'matching_keys' => 'setMatchingKeys',
        'sources_count' => 'setSourcesCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attribute_mappings' => 'getAttributeMappings',
        'enabled' => 'getEnabled',
        'main_component_id' => 'getMainComponentId',
        'matching_keys' => 'getMatchingKeys',
        'sources_count' => 'getSourcesCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('attribute_mappings', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('main_component_id', $data ?? [], null);
        $this->setIfExists('matching_keys', $data ?? [], null);
        $this->setIfExists('sources_count', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attribute_mappings
     *
     * @return \criteo\api\retailmedia\experimental\Model\MultiSourceAttributeMapping[]|null
     */
    public function getAttributeMappings()
    {
        return $this->container['attribute_mappings'];
    }

    /**
     * Sets attribute_mappings
     *
     * @param \criteo\api\retailmedia\experimental\Model\MultiSourceAttributeMapping[]|null $attribute_mappings Attribute-level mapping rules applied during enrichment.
     *
     * @return self
     */
    public function setAttributeMappings($attribute_mappings)
    {
        if (is_null($attribute_mappings)) {
            array_push($this->openAPINullablesSetToNull, 'attribute_mappings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attribute_mappings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attribute_mappings'] = $attribute_mappings;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled Whether Multi-Source Catalog was enabled for this ingestion.
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets main_component_id
     *
     * @return int|null
     */
    public function getMainComponentId()
    {
        return $this->container['main_component_id'];
    }

    /**
     * Sets main_component_id
     *
     * @param int|null $main_component_id Identifier of the primary catalog component.
     *
     * @return self
     */
    public function setMainComponentId($main_component_id)
    {
        if (is_null($main_component_id)) {
            throw new \InvalidArgumentException('non-nullable main_component_id cannot be null');
        }
        $this->container['main_component_id'] = $main_component_id;

        return $this;
    }

    /**
     * Gets matching_keys
     *
     * @return string[]|null
     */
    public function getMatchingKeys()
    {
        return $this->container['matching_keys'];
    }

    /**
     * Sets matching_keys
     *
     * @param string[]|null $matching_keys Keys used to match products between the primary catalog and the additional sources.
     *
     * @return self
     */
    public function setMatchingKeys($matching_keys)
    {
        if (is_null($matching_keys)) {
            array_push($this->openAPINullablesSetToNull, 'matching_keys');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('matching_keys', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['matching_keys'] = $matching_keys;

        return $this;
    }

    /**
     * Gets sources_count
     *
     * @return int|null
     */
    public function getSourcesCount()
    {
        return $this->container['sources_count'];
    }

    /**
     * Sets sources_count
     *
     * @param int|null $sources_count Number of additional sources configured, excluding the primary catalog.
     *
     * @return self
     */
    public function setSourcesCount($sources_count)
    {
        if (is_null($sources_count)) {
            throw new \InvalidArgumentException('non-nullable sources_count cannot be null');
        }
        $this->container['sources_count'] = $sources_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


