<?php
/**
 * PageMeta
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\retailmedia\preview
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Preview
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\retailmedia\preview\Model;

use \ArrayAccess;
use \criteo\api\retailmedia\preview\ObjectSerializer;

/**
 * PageMeta Class Doc Comment
 *
 * @category Class
 * @description Represents metadata for paginated data, including information about the current page, page size,  total items, and  total pages in a search result.
 * @package  criteo\api\retailmedia\preview
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PageMeta implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PageMeta';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'current_page_index' => 'int',
        'current_page_size' => 'int',
        'total_items_across_all_pages' => 'int',
        'total_pages' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'current_page_index' => 'int32',
        'current_page_size' => 'int32',
        'total_items_across_all_pages' => 'int64',
        'total_pages' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'current_page_index' => true,
		'current_page_size' => true,
		'total_items_across_all_pages' => true,
		'total_pages' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_page_index' => 'currentPageIndex',
        'current_page_size' => 'currentPageSize',
        'total_items_across_all_pages' => 'totalItemsAcrossAllPages',
        'total_pages' => 'totalPages'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_page_index' => 'setCurrentPageIndex',
        'current_page_size' => 'setCurrentPageSize',
        'total_items_across_all_pages' => 'setTotalItemsAcrossAllPages',
        'total_pages' => 'setTotalPages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_page_index' => 'getCurrentPageIndex',
        'current_page_size' => 'getCurrentPageSize',
        'total_items_across_all_pages' => 'getTotalItemsAcrossAllPages',
        'total_pages' => 'getTotalPages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('current_page_index', $data ?? [], 0);
        $this->setIfExists('current_page_size', $data ?? [], 25);
        $this->setIfExists('total_items_across_all_pages', $data ?? [], null);
        $this->setIfExists('total_pages', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['current_page_index']) && ($this->container['current_page_index'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'current_page_index', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['current_page_index']) && ($this->container['current_page_index'] < 0)) {
            $invalidProperties[] = "invalid value for 'current_page_index', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['current_page_size']) && ($this->container['current_page_size'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'current_page_size', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['current_page_size']) && ($this->container['current_page_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'current_page_size', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_page_index
     *
     * @return int|null
     */
    public function getCurrentPageIndex()
    {
        return $this->container['current_page_index'];
    }

    /**
     * Sets current_page_index
     *
     * @param int|null $current_page_index The 0 indexed page index you would like to receive given the page size
     *
     * @return self
     */
    public function setCurrentPageIndex($current_page_index)
    {
        if (is_null($current_page_index)) {
            array_push($this->openAPINullablesSetToNull, 'current_page_index');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_page_index', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($current_page_index) && ($current_page_index > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $current_page_index when calling PageMeta., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($current_page_index) && ($current_page_index < 0)) {
            throw new \InvalidArgumentException('invalid value for $current_page_index when calling PageMeta., must be bigger than or equal to 0.');
        }

        $this->container['current_page_index'] = $current_page_index;

        return $this;
    }

    /**
     * Gets current_page_size
     *
     * @return int|null
     */
    public function getCurrentPageSize()
    {
        return $this->container['current_page_size'];
    }

    /**
     * Sets current_page_size
     *
     * @param int|null $current_page_size The maximum number of items you would like to receive in this request
     *
     * @return self
     */
    public function setCurrentPageSize($current_page_size)
    {
        if (is_null($current_page_size)) {
            array_push($this->openAPINullablesSetToNull, 'current_page_size');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('current_page_size', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($current_page_size) && ($current_page_size > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $current_page_size when calling PageMeta., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($current_page_size) && ($current_page_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $current_page_size when calling PageMeta., must be bigger than or equal to 1.');
        }

        $this->container['current_page_size'] = $current_page_size;

        return $this;
    }

    /**
     * Gets total_items_across_all_pages
     *
     * @return int|null
     */
    public function getTotalItemsAcrossAllPages()
    {
        return $this->container['total_items_across_all_pages'];
    }

    /**
     * Sets total_items_across_all_pages
     *
     * @param int|null $total_items_across_all_pages Total Items in search result across all pages
     *
     * @return self
     */
    public function setTotalItemsAcrossAllPages($total_items_across_all_pages)
    {
        if (is_null($total_items_across_all_pages)) {
            array_push($this->openAPINullablesSetToNull, 'total_items_across_all_pages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_items_across_all_pages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_items_across_all_pages'] = $total_items_across_all_pages;

        return $this;
    }

    /**
     * Gets total_pages
     *
     * @return int|null
     */
    public function getTotalPages()
    {
        return $this->container['total_pages'];
    }

    /**
     * Sets total_pages
     *
     * @param int|null $total_pages total pages in search result
     *
     * @return self
     */
    public function setTotalPages($total_pages)
    {
        if (is_null($total_pages)) {
            array_push($this->openAPINullablesSetToNull, 'total_pages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_pages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_pages'] = $total_pages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


