<?php
/**
 * RmUserBehaviorV1
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  criteo\api\retailmedia\preview
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Criteo API
 *
 * Criteo API - RetailMedia
 *
 * The version of the OpenAPI document: Preview
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace criteo\api\retailmedia\preview\Model;

use \ArrayAccess;
use \criteo\api\retailmedia\preview\ObjectSerializer;

/**
 * RmUserBehaviorV1 Class Doc Comment
 *
 * @category Class
 * @description Settings to target users based on their behavior
 * @package  criteo\api\retailmedia\preview
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RmUserBehaviorV1 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RmUserBehaviorV1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'shopper_activity' => 'string',
        'lookback_days' => 'string',
        'category_ids' => 'string[]',
        'brand_ids' => 'string[]',
        'min_price' => 'float',
        'max_price' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'shopper_activity' => null,
        'lookback_days' => null,
        'category_ids' => null,
        'brand_ids' => null,
        'min_price' => 'double',
        'max_price' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'shopper_activity' => true,
		'lookback_days' => true,
		'category_ids' => true,
		'brand_ids' => true,
		'min_price' => true,
		'max_price' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shopper_activity' => 'shopperActivity',
        'lookback_days' => 'lookbackDays',
        'category_ids' => 'categoryIds',
        'brand_ids' => 'brandIds',
        'min_price' => 'minPrice',
        'max_price' => 'maxPrice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shopper_activity' => 'setShopperActivity',
        'lookback_days' => 'setLookbackDays',
        'category_ids' => 'setCategoryIds',
        'brand_ids' => 'setBrandIds',
        'min_price' => 'setMinPrice',
        'max_price' => 'setMaxPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shopper_activity' => 'getShopperActivity',
        'lookback_days' => 'getLookbackDays',
        'category_ids' => 'getCategoryIds',
        'brand_ids' => 'getBrandIds',
        'min_price' => 'getMinPrice',
        'max_price' => 'getMaxPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SHOPPER_ACTIVITY_UNKNOWN = 'Unknown';
    public const SHOPPER_ACTIVITY_VIEW = 'View';
    public const SHOPPER_ACTIVITY_BUY = 'Buy';
    public const SHOPPER_ACTIVITY_ADD_TO_CART = 'AddToCart';
    public const LOOKBACK_DAYS_UNKNOWN = 'Unknown';
    public const LOOKBACK_DAYS_LAST7_DAYS = 'Last7Days';
    public const LOOKBACK_DAYS_LAST14_DAYS = 'Last14Days';
    public const LOOKBACK_DAYS_LAST30_DAYS = 'Last30Days';
    public const LOOKBACK_DAYS_LAST45_DAYS = 'Last45Days';
    public const LOOKBACK_DAYS_LAST60_DAYS = 'Last60Days';
    public const LOOKBACK_DAYS_LAST90_DAYS = 'Last90Days';
    public const LOOKBACK_DAYS_LAST120_DAYS = 'Last120Days';
    public const LOOKBACK_DAYS_LAST150_DAYS = 'Last150Days';
    public const LOOKBACK_DAYS_LAST180_DAYS = 'Last180Days';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getShopperActivityAllowableValues()
    {
        return [
            self::SHOPPER_ACTIVITY_UNKNOWN,
            self::SHOPPER_ACTIVITY_VIEW,
            self::SHOPPER_ACTIVITY_BUY,
            self::SHOPPER_ACTIVITY_ADD_TO_CART,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLookbackDaysAllowableValues()
    {
        return [
            self::LOOKBACK_DAYS_UNKNOWN,
            self::LOOKBACK_DAYS_LAST7_DAYS,
            self::LOOKBACK_DAYS_LAST14_DAYS,
            self::LOOKBACK_DAYS_LAST30_DAYS,
            self::LOOKBACK_DAYS_LAST45_DAYS,
            self::LOOKBACK_DAYS_LAST60_DAYS,
            self::LOOKBACK_DAYS_LAST90_DAYS,
            self::LOOKBACK_DAYS_LAST120_DAYS,
            self::LOOKBACK_DAYS_LAST150_DAYS,
            self::LOOKBACK_DAYS_LAST180_DAYS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('shopper_activity', $data ?? [], null);
        $this->setIfExists('lookback_days', $data ?? [], null);
        $this->setIfExists('category_ids', $data ?? [], null);
        $this->setIfExists('brand_ids', $data ?? [], null);
        $this->setIfExists('min_price', $data ?? [], null);
        $this->setIfExists('max_price', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getShopperActivityAllowableValues();
        if (!is_null($this->container['shopper_activity']) && !in_array($this->container['shopper_activity'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'shopper_activity', must be one of '%s'",
                $this->container['shopper_activity'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLookbackDaysAllowableValues();
        if (!is_null($this->container['lookback_days']) && !in_array($this->container['lookback_days'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'lookback_days', must be one of '%s'",
                $this->container['lookback_days'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shopper_activity
     *
     * @return string|null
     */
    public function getShopperActivity()
    {
        return $this->container['shopper_activity'];
    }

    /**
     * Sets shopper_activity
     *
     * @param string|null $shopper_activity Reach people who performed specific action
     *
     * @return self
     */
    public function setShopperActivity($shopper_activity)
    {
        if (is_null($shopper_activity)) {
            array_push($this->openAPINullablesSetToNull, 'shopper_activity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('shopper_activity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getShopperActivityAllowableValues();
        if (!is_null($shopper_activity) && !in_array($shopper_activity, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'shopper_activity', must be one of '%s'",
                    $shopper_activity,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['shopper_activity'] = $shopper_activity;

        return $this;
    }

    /**
     * Gets lookback_days
     *
     * @return string|null
     */
    public function getLookbackDays()
    {
        return $this->container['lookback_days'];
    }

    /**
     * Sets lookback_days
     *
     * @param string|null $lookback_days The number of days to look back
     *
     * @return self
     */
    public function setLookbackDays($lookback_days)
    {
        if (is_null($lookback_days)) {
            array_push($this->openAPINullablesSetToNull, 'lookback_days');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lookback_days', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getLookbackDaysAllowableValues();
        if (!is_null($lookback_days) && !in_array($lookback_days, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'lookback_days', must be one of '%s'",
                    $lookback_days,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['lookback_days'] = $lookback_days;

        return $this;
    }

    /**
     * Gets category_ids
     *
     * @return string[]|null
     */
    public function getCategoryIds()
    {
        return $this->container['category_ids'];
    }

    /**
     * Sets category_ids
     *
     * @param string[]|null $category_ids The list of category ids
     *
     * @return self
     */
    public function setCategoryIds($category_ids)
    {
        if (is_null($category_ids)) {
            array_push($this->openAPINullablesSetToNull, 'category_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('category_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['category_ids'] = $category_ids;

        return $this;
    }

    /**
     * Gets brand_ids
     *
     * @return string[]|null
     */
    public function getBrandIds()
    {
        return $this->container['brand_ids'];
    }

    /**
     * Sets brand_ids
     *
     * @param string[]|null $brand_ids The list of brand ids
     *
     * @return self
     */
    public function setBrandIds($brand_ids)
    {
        if (is_null($brand_ids)) {
            array_push($this->openAPINullablesSetToNull, 'brand_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('brand_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['brand_ids'] = $brand_ids;

        return $this;
    }

    /**
     * Gets min_price
     *
     * @return float|null
     */
    public function getMinPrice()
    {
        return $this->container['min_price'];
    }

    /**
     * Sets min_price
     *
     * @param float|null $min_price Minimum price of the products
     *
     * @return self
     */
    public function setMinPrice($min_price)
    {
        if (is_null($min_price)) {
            array_push($this->openAPINullablesSetToNull, 'min_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_price'] = $min_price;

        return $this;
    }

    /**
     * Gets max_price
     *
     * @return float|null
     */
    public function getMaxPrice()
    {
        return $this->container['max_price'];
    }

    /**
     * Sets max_price
     *
     * @param float|null $max_price Maximum price of the products
     *
     * @return self
     */
    public function setMaxPrice($max_price)
    {
        if (is_null($max_price)) {
            array_push($this->openAPINullablesSetToNull, 'max_price');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_price', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_price'] = $max_price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


